### ISSUE TITLE
How to make it run in a browser environment.

### ISSUE THREAD

**Issue by kiwiflydream** [hamedpa/twitster#20]
It seems that the inability to run in a browser is due to reliance on node.js modules.

**Comment by aliMoradi2005** [comment]
You cannot use this package directly in the browser. If you want to use it, you need to integrate it into your backend API. Alternatively, you can use the official API provided for this purpose.

**Comment by kiwiflydream** [comment]
> You cannot use this package directly in the browser. If you want to use it, you need to integrate it into your backend API. Alternatively, you can use the official API provided for this purpose.

thank you
